theme: jekyll-theme-cayman
timezone: Asia/Shanghai

url: http://vincenttam.github.io
title: Blog
author: lscpku
simple_search: https://google.com/search
description: Audere est Facere!
date_format: ordinal